project:
  type: website
  output-dir: "."

website:
  title: "Blaise Leone"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
      - text: classwork
        href: danl-200-cw-10.qmd
      
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© Blaise Leone, 2023"

format:
  html:
    theme: 
      light: cyborg
      dark: darkly
    mainfont: system-ui; 
    highlight-style: espresso
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    

execute: 
  warning: false
  message: false