project:
  type: website
  output-dir: "."

website:
  title: "Blaise Leone"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
      - text: template
        href: quarto-template-2.qmd
    right:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
      - text: Homeowrk
        href: hw.qmd
    
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© YOUR NAME, 2023"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
